"use client";

export default function DraftBanner() {
  return (
    <div className="bg-alert text-white px-8 py-5 flex items-start gap-6" role="alert">
      <span
        className="shrink-0 font-grotesk font-black text-2xl tracking-[0.12em] uppercase leading-none pt-0.5"
        aria-hidden="true"
      >
        DRAFT
      </span>
      <div className="w-px self-stretch bg-white/30" />
      <div>
        <p className="font-grotesk font-semibold text-sm tracking-wide uppercase leading-none mb-1">
          Not approved — not for clinical use
        </p>
        <p className="text-white/80 text-sm font-grotesk leading-relaxed">
          This note was generated by AI and has not been reviewed. It must not inform clinical
          decisions until a clinician verifies and signs off below.
        </p>
      </div>
    </div>
  );
}
