"""scribe.domain — frozen domain vocabulary (design.md §1)."""

from scribe.domain.types import (
    Approver,
    ApprovedNote,
    Audio,
    Claim,
    Dialogue,
    DocumentRef,
    Draft,
    DraftStatus,
    EditedDraft,
    EvalReport,
    GroundedNote,
    PatientContext,
    Provenance,
    Role,
    SOAPNote,
    SpanRef,
    SpeakerTurn,
    TimeSpan,
    TranscriptSeg,
    Utterance,
    WordTiming,
)

__all__ = [
    "Approver",
    "ApprovedNote",
    "Audio",
    "Claim",
    "Dialogue",
    "DocumentRef",
    "Draft",
    "DraftStatus",
    "EditedDraft",
    "EvalReport",
    "GroundedNote",
    "PatientContext",
    "Provenance",
    "Role",
    "SOAPNote",
    "SpanRef",
    "SpeakerTurn",
    "TimeSpan",
    "TranscriptSeg",
    "Utterance",
    "WordTiming",
]
